steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Building image'
    args: ['build', '--no-cache', '-t', 'gcr.io/tcb-web/work-image', '.']

images: ['gcr.io/tcb-web/work-image']
timeout: 60m
