# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# Disable the AWS module.
[aws]
disabled = true

# Disable the AWS module.
[gcloud]
disabled = true

[terraform]
format = "[tf = $workspace]($style) "

[docker]
symbol = " "
