format = """
$directory\
$git_branch\
$git_status\
$time\
$env_var\
\n$character"""


[character]
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
truncation_length = 8
truncation_symbol = ""

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"



[time]
disabled = false
time_format = "%T"
utc_time_offset = "-5"

[env_var]
format = "[$env_value]($style)"
variable = "SESSION_NAME"
style = "blod blue"
